services:
  jr-pass-map:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    container_name: jr-pass-map
    restart: unless-stopped
    networks:
      jrpm-net:
        ipv4_address: 172.28.0.10

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: jrpm-db
    environment:
      POSTGRES_DB: jrpm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/docker-entrypoint-initdb.d/data
    networks:
      jrpm-net:
        ipv4_address: 172.28.0.11

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: jrpm-api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/jrpm
    depends_on:
      - db
    ports:
      - "5050:5050"
    restart: unless-stopped
    networks:
      jrpm-net:
        ipv4_address: 172.28.0.12

volumes:
  pgdata:

networks:
  jrpm-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
    driver_opts:
      com.docker.network.driver.mtu: 1450